[media-tank]
  use_template = production
  recursive = no

[media-tank/postgres]
  use_template = database
  recursive = no

[media-tank/mysql]
  use_template = database
  recursive = no

[music-tank]
  use_template = production
  recursive = yes

[backup-tank/media-mirror]
  use_template = backup
  recursive = yes

[backup-tank/music-tank]
  use_template = backup
  recursive = yes

[backup-tank/ssd-cache-mirror]
  use_template = cache_mirror
  recursive = yes

[template_production]
  autosnap = yes
  autoprune = yes
  daily = 14
  monthly = 0
  yearly = 0
  daily_hour = 4
  daily_min = 0

[template_database]
  use_template = production
  pre_snapshot_script = /opt/db-flush.sh

[template_backup]
  autosnap = no
  autoprune = yes
  daily = 15
  monthly = 0
  yearly = 0

[template_cache_mirror]
  autosnap = yes
  autoprune = yes
  daily = 7
  monthly = 0
  yearly = 0
  daily_hour = 4
  daily_min = 15
